#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< HEAD
# Generated by Vivado on Thu May 09 23:32:55 CEST 2024
=======
# Generated by Vivado on Fri May 10 14:50:09 CEST 2024
>>>>>>> 53d3410 (timer)
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_master_protocol_behav -key {Behavioral:sim_1:Functional:tb_master_protocol} -tclbatch tb_master_protocol.tcl -log simulate.log"
xsim tb_master_protocol_behav -key {Behavioral:sim_1:Functional:tb_master_protocol} -tclbatch tb_master_protocol.tcl -log simulate.log

